# Site settings
title: SBST
description: We are a cross-agency team with backgrounds in a diversity of fields, including economics, policy, psychology, law, medicine, statistics and political science. What unifies us is our commitment to using what research tells us about how people make decisions to better serve Americans and improve government efficiency.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
logo: /assets/img/logo.png

colors:
  background: '#fdfdfd'
  brand: '#2a7ae2'
  button: 'rgb(239, 91, 93)'
  text: 'rgb(45, 97, 114)'
  contact: 'rgb(248, 235, 212)'

analytics:
  google:
    code: '<<UA-CODE-TO-COME>>'
  dap:
    agency: GSA
    subagency: SBST


contact:
  agencyname: Social & Behavioral Sciences Team
  agencyimage: /assets/img/gsa-logo.png
  email: sbst@gsa.gov
  form:
    url: https://docs.google.com/forms/d/1Tsdm_2spbxWnmTFMrH5eHxpOAN9W4LB3eaMMXJ1N0rU/formResponse
    email: entry.1440502332
    hidden:
      name: fbzx
      value: -7861934959779167198


# Build settings
markdown: kramdown
